site_name: dbdev
site_url: https://supabase.github.io/dbdev
site_description: A package manager for PostgreSQL trusted language extensions

repo_name: supabase/dbdev
repo_url: https://github.com/supabase/dbdev

nav:
    - Welcome: 'welcome.md'
    - SQL Client: 'sql-client.md'
    - CLI: 'cli.md'

theme:
    name: 'material'
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase.github.io/dbdev
    features:
      - navigation.expand
    palette:
        primary: black
        accent: light green

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
        guess_lang: false
        use_pygments: true
        pygments_style: default
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - pymdownx.tasklist
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
