site_name: dbdev
site_url: https://supabase.github.io/dbdev
site_description: A package manager for PostgreSQL trusted language extensions

repo_name: supabase/dbdev
repo_url: https://github.com/supabase/dbdev

nav:
    - Welcome: 'index.md'
    - Using the CLI: 'cli.md'
    - Publish a Package: 'publish-extension.md'
    - Install a Package: 'install-a-package.md'
    - Structure of a Postgres Extension: 'extension_structure.md'

theme:
    name: 'material'
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase.github.io/dbdev
    features:
      - navigation.expand
      - content.code.copy
    palette:
        primary: black
        accent: light green

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
        guess_lang: false
        use_pygments: true
        pygments_style: default
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - pymdownx.tasklist
    - admonition
