[package]
name = "dbdev"
version = "0.1.6"
edition = "2021"
authors = ["supabase"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
dirs = "5.0.1"
futures = "0.3"
postgrest = "1.5.0"
regex = "1.9"
reqwest = { version = "0.11.14", features = ["json", "native-tls-vendored"] }
rpassword = "7.2.0"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
sqlx = { version = "0.8.1", features = [
    "postgres",
    "chrono",
    "uuid",
    "runtime-tokio-rustls",
] }
thiserror = "1.0.38"
tokio = { version = "1", features = ["full"] }
toml = { version = "0.7.6", features = ["preserve_order"] }
url = { version = "2.5.4", features = ["serde"] }
uuid = { version = "1.3.0", features = ["serde"] }
