name: CLI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --release --verbose
        working-directory: ./cli
      - name: Run tests
        run: cargo test --release --verbose
        working-directory: ./cli
