name: pgTAP Tests
on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: 1.127.4
      - name: Supabase Start
        run: supabase start
      - name: Run Tests
        run: supabase test db
