name: pre-commit hooks

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: set up python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: run static analysis
      run: |
        pre-commit run --all-files
