name: Check Website Code Formatting with Prettier

on:
  pull_request:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run Prettier
        uses: creyD/prettier_action@v4.6
        with:
          # Prettier CLI arguments
          prettier_options: '--config ./website/.prettierrc --ignore-path ./website/.prettierignore --check ./website'
