name: Check Website Code Formatting with Prettier

on:
  pull_request:
    branches:
      - 'master'

jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          # Prettier CLI arguments
          prettier_options: '--check .'
          working_directory: 'website/'
