name: Release CLI

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            TODO: Write release notes
          draft: false
          prerelease: false

  build:
    name: Release Artifacts
    needs:
      - create-release
    strategy:
      matrix:
        box:
          - { runner: ubuntu-20.04, os-and-arch: linux-amd64 }
          - { runner: arm-runner, os-and-arch: linux-arm64 }
          - { runner: macos-12, os-and-arch: macos-arm64 }
    runs-on: ${{ matrix.box.runner }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Build on linux
        if: ${{ matrix.box.os-and-arch == 'linux-amd64' ||  matrix.box.os-and-arch == 'linux-arm64' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl build-essential libssl-dev pkg-config

          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile minimal --default-toolchain stable
          source "$HOME/.cargo/env"
          rustup --version && rustc --version && cargo --version

          cd cli && \
          cargo build --release && \
          cd ./target/release && \
          tar -czvf dbdev.tar.gz ./dbdev

      - uses: actions/checkout@v3
      - name: Build on macOS
        if: ${{ matrix.box.os-and-arch == 'macos-arm64' }}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile minimal --default-toolchain stable
          source "$HOME/.cargo/env"
          rustup --version && rustc --version && cargo --version

          cd cli && \
          cargo build --release && \
          cd ./target/release && \
          tar -czvf dbdev.tar.gz ./dbdev

      - name: Get Upload Url
        run: echo UPLOAD_URL=$(curl --silent https://api.github.com/repos/${{ github.repository }}/releases/latest | jq .upload_url --raw-output) >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./cli/target/release/dbdev.tar.gz
          asset_name: dbdev-${{ github.ref_name }}-${{ matrix.box.os-and-arch }}.tar.gz
          asset_content_type: application/gzip
