name: Release Scoop Bucket

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      scoop_bucket_rw:
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: supabase/scoop-bucket
          ref: "main"
          token: ${{ secrets.scoop_bucket_rw }}
          fetch-depth: 0

      - name: Compute tag and version
        id: vars
        run: |
          tag="${{ inputs.tag }}"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          # strip the leading v (if present)
          echo "version=${tag#v}" >> "$GITHUB_OUTPUT"

      - name: Download Windows AMD64 package
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "supabase/dbdev"
          tag: ${{ inputs.tag }}
          fileName: "dbdev-${{ inputs.tag }}-windows-amd64.zip"

      - name: Generate Manifest File
        run: |
          windows_amd64_hash=`shasum -a 256 dbdev-${{ inputs.tag }}-windows-amd64.zip | cut -d" " -f1`

          version="${{ steps.vars.outputs.version }}"

          # update dbdev.json file
          echo '{' > dbdev.json
          echo "    \"version\": \"${version}\"," >> dbdev.json
          echo '    "architecture": {' >> dbdev.json
          echo '        "64bit": {' >> dbdev.json
          echo "            \"url\": \"https://github.com/supabase/dbdev/releases/download/v${version}/dbdev-v${version}-windows-amd64.zip\"," >> dbdev.json
          echo '            "bin": [' >> dbdev.json
          echo '                "dbdev.exe"' >> dbdev.json
          echo '            ],' >> dbdev.json
          echo "            \"hash\": \"${windows_amd64_hash}\"" >> dbdev.json
          echo '        }' >> dbdev.json
          echo '    },' >> dbdev.json
          echo '    "homepage": "https://database.dev",' >> dbdev.json
          echo '    "license": "Apache",' >> dbdev.json
          echo '    "description": "CLI to help publish extensions to database.dev"' >> dbdev.json
          echo '}' >> dbdev.json
          echo ''

          # prepare a PR body file with some context
          echo "This PR updates the Scoop manifest for dbdev to version v${version}." > PR_BODY.md
          echo >> PR_BODY.md
          echo "It was auto-generated by the dbdev release workflow." >> PR_BODY.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.scoop_bucket_rw }}
          commit-message: "Release dbdev version v${{ steps.vars.outputs.version }}"
          title: "Release dbdev version v${{ steps.vars.outputs.version }}"
          body-path: PR_BODY.md
          add-paths: |
            dbdev.json
          branch: "dbdev/update/v${{ steps.vars.outputs.version }}"
          base: "main"
          committer: "dbdev release-scoop-bucket.yaml workflow <raminder@supabase.io>"
          author: "dbdev release-scoop-bucket.yaml workflow <raminder@supabase.io>"
