name: Call a reusable workflow

on:
  push:
    branches:
      - chore/release-workflow

jobs:
  call-release-workflow:
    uses: ./.github/workflows/release-homebrew-tap.yaml
    with:
      tag: v0.1.2
      homebrew_tap_rw: ${{ secrets.HOMEBREW_TAP_RW }}
